### ISSUE TITLE
Allow Consumers to set border box to all elements

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#165]
### Describe the bug
It is convenient that consumers may set `box-sizing: border-box;` to all elements, i.e. 

```css
html, body, *, ::before, ::after {
  box-sizing: border-box;
}
```

The elements should support these configurations. However, I identified that the `ino-input` and `ino-chip` components do not understand this.

### Expected behavior
The element's behavior exactly the same.

### Possible Solution
(To debug): Set the border-box setting within the storybook)
1. Override the border-box setting for all needed elements (ino-chip and ino-input for sure) with

```css
& * {
    box-sizing: initial;
  }
```
