### ISSUE TITLE
Canary releases

### ISSUE THREAD

**Issue by pfecht** [inovex/elements#167]
Add canary releases in order to provide consumers a fast way to upgrade to new features.

### Describe the solution you'd like
It would make the development much easier if the latest master would always be published to npm registry as canary deployment.

### Additional context
Lerna has such a feature and we could add such a script to package.json

```json
 "publish:canary": "yarn lerna publish --canary --exact --preid next.$(git rev-parse --short HEAD) --force-publish='*'"
```

This deploys a new version under the tag `canary` (we can change the tag with `--dist-tag`) and adds a version based on the last commit hash. It forces all packages to create a canary release and use the exact version to overcome conflicts resolving the correct version.

Canary deployments neither create a git commit nor a tag. We can add such canary release to the github pipeline in a similar way to the following gitlab ci script step:

```yaml
publish_package:
  stage: publish
  script:
    - PUPPETEER_SKIP_DOWNLOAD=true yarn 
    - yarn publish:canary
  only:
    - master
```

This requires the pipeline to be able to publish to npm registry.
