### ISSUE TITLE
ino-card: Inherit common attributes

### ISSUE THREAD

**Issue by janivo** [inovex/elements#232]
Same as in #231 but with the `ino-card` component.

Additional attributes which should be inherited:
- `height`
- `width`
- `margin` (maybe?)
- `padding` (maybe?)

**Possible solution**:
```css
div {
  width: inherit;
}
```
