### ISSUE TITLE
ino-segment-group: Animate value change

### ISSUE THREAD

**Issue by janivo** [inovex/elements#737]
Updating the value of the ino-segment-group should have a smooth slide animation.

e.g. tab-bar:

![Image](https://user-images.githubusercontent.com/22963121/190435900-0d304b88-357b-4bc4-a50c-29d63c47fbfc.gif)

## Inspiration

**`ino-segmented-control-group.scss`** 
```scss

@use 'base/theme';
@use '../ino-segmented-control';

$padding: 4px;
$border-radius-outer: 18px;
$border-radius-inner: 14px;
$transition: 300ms ease-in-out;

ino-segmented-control-group {
  /**
   * @prop --ino-segmented-control-width: Width of each Segmented Control
   * @prop --ino-segmented-control-height: Height of each Segmented Control
  */
  $control-width: var(--ino-segmented-control-width, 120px);
  $control-height: var(--ino-segmented-control-height, 28px);
  
  box-sizing: border-box;
  outline: 0;

  fieldset {
    box-sizing: border-box;
    display: inline-flex;
    background-color: #EFF1F3; // TODO: Move color
    border-radius: $border-radius-outer;
    padding: $padding;
    margin: 0;
    border: none;
    transition: background-color $transition;
  }

  legend {
    visibility: hidden;
    overflow: hidden;
    height: 0;
    width: 0;
  }

  .ino-segmented-control-group__controls { 
    position: relative;
    display: flex;
  }

  // Dimensions and active background

  ino-segmented-control,
  .ino-segmented-control-group__active-background {
    width: $control-width;
    height: $control-height;
  }

  .ino-segmented-control-group__active-background {
    background: #ffffff;
    box-shadow: 0px 1px 2px rgba(30, 33, 37, 0.1);
    border-radius: 14px;
    position: absolute;
    left: 0px;
    top: 0;
    transform: translateX(0);
    transition: transform 0.5s ease-in-out;
  }

  &.ino-segmented-control-group--no-value .ino-segmented-control-group__active-background {
    box-shadow: none;
    background-color: transparent;
  }

  // Generate transition calculations for 8 max columns. Should be enough.
  ino-segmented-control.ino-segmented-control--checked {
    @for $i from 1 through 7 {
      &:nth-child(#{$i + 1}) ~ .ino-segmented-control-group__active-background {
        transform: translateX(calc(#{$i} * #{$control-width}));
        transition: transform $transition;
      }
    }
  }

  // disabled state
  fieldset:disabled {
    background-color: rgba(#EFF1F3, 0.8); // TODO: Move color
    cursor: initial;    
    @include ino-segmented-control.disabled;
  }

  // hover state
  fieldset:not(:disabled):hover, 
  fieldset:not(:disabled):focus-within {
    background-color: #DBE0E5;    
    @include ino-segmented-control.hover;
  }

  // focus state
  fieldset:not(:disabled):focus {
    background-color: #DBE0E5;
    border: 2px solid #f7bcc6;
  }
  fieldset:not(:disabled) {
    @include ino-segmented-control.focus;
  }
}
```

`ino-segment-group/_index.scss`

```scss
@use 'base/theme';

@mixin hover {
  ino-segmented-control:not(.ino-segmented-control--checked) label:hover {
    background: rgba(255, 255, 255, 0.3);
    box-shadow: 0px 1px 2px rgba(30, 33, 37, 0.1)
  }
}

@mixin disabled {
  ino-segmented-control {
    label {
      color: theme.color(light);
      cursor: initial;
    }
  }
}

@mixin focus {
  ino-segmented-control label:focus {
    background: rgba(255, 255, 255, 0.3);
    box-shadow: 0px 1px 2px rgba(30, 33, 37, 0.1)
  }
}

```

`ino-segment-button.scss`

```scss
@use 'base/theme';
@use 'base/typography';

$label-height: 28px;
$label-padding: 32px;
$border-radius-inner: 14px;

// Only contains basic styling, hover, active and focus states are controlled by
// the parent ino-segmented-control-group
ino-segmented-control {
  display: inline-flex;

  --ino-icon-height: 24px;
  --ino-icon-width: 24px;
  --ino-icon-color: currentColor;

  input {
    appearance: none;
    position: absolute;
  }

  label {
    @include typography.font(sans-serif, s, semibold);
    color: theme.text-color(gray-2);
    will-change: color;
    border-radius: $border-radius-inner;
    outline: 0;
    z-index: 1;
    width: 100%;
    height: 100%;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    box-sizing: border-box;
    user-select: none;
  }

  // Checked
  &.ino-segmented-control--checked label {
    transition: color 0.3s ease-in;
    color: theme.color(primary);
    cursor: unset;
    pointer-events: none;
  }
}
```
